name: CI # как назвать - выбираете сами

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # move to another branch or repository
      - run: docker build . -t builder
      - run: docker run -v "$(pwd):/app" builder build
      - uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: build